### ISSUE TITLE
this project fail to run due to SelectableText class fail to trace the correct source

### ISSUE THREAD

**Issue by renntbenrennt** [jamesblasco/selection_controls_example#1]
![image](https://user-images.githubusercontent.com/13610283/95616893-26153780-0a9d-11eb-80c0-6f7498f11837.png)

As the screenshot indicates and I assume the `SelectableText` here should be a custom one not the one from material package, which is in effect on my machine, which is why it failed
![image](https://user-images.githubusercontent.com/13610283/95617235-ab98e780-0a9d-11eb-9105-e79ff2f7da4a.png)

how should I resolve this and run the project successfully?

Thanks in advance!

Ps, this is my flutter doctor log:
![image](https://user-images.githubusercontent.com/13610283/95617365-e4d15780-0a9d-11eb-985d-d00a81f35eb2.png)

Pss, I'm coming from issue #36985 where you mentioned this awesome work, which is exactly what we want in our next project, I have been scratching my head since the project begin and I was aware that the Flutter code base lack this customizable selection control support, I was desperate for quite a while until I found your work and the issue you brought up, I hope this work can be publish eventually because there are hundreds of thousands people want this.

Thanks!

**Comment by jamesblasco** [comment]
Hello, this is a demo that requires this PR to be approved
https://github.com/flutter/flutter/pull/66785

You can use the flutter version of that branch to try it. But probably is not going to be approved as something similar to this example  is going to be built inside the flutter framework

**Comment by renntbenrennt** [comment]
Hey, James, thanks for responding, but I have a question that, my local
Flutter sdk was downloaded as a zip file, but in your suggestion, in order
to make this demo works, should I switch sdk to a GitHub clone then inside
the clone project switch to the branch you were mentioning, then I can run
the demo?

**Comment by jamesblasco** [comment]
Yes, you clone my fork of flutter and change to that branch. Then call flutter from that path instead of the default you have.

In vscode you can set multiple flutter paths and change them when you want

**Comment by renntbenrennt** [comment]
Hey man, I cloned your flutter sdk from that PR, but when I set the path to it, my ide, Android Studio just went nut and said SDK is incomplete.... any idea what's wrong?

![image](https://user-images.githubusercontent.com/13610283/95686629-a7053800-0c31-11eb-9c7d-d712adb9989a.png)

**Comment by jamesblasco** [comment]
Could you try to use the path `......./jamesblasco/flutter/bin`?

**Comment by renntbenrennt** [comment]
hey, thanks for responding, and yes I have tried that, not working as well.

But I have your example running locally now.

By making a copy of my working flutter sdk and directly change it with your version's flutter as guide from that PR.

And I have to say that your work is incredibly awesome!!!!!! Thank you man!!!!

Although I do have a question, if turning your example into a package, does that also rely on a certain version's flutter? 

I mean, there's no way to do this sort of customization without the actual change in the Flutter codebase, like, adding selectionControl to editableText, right?

Thanks again, you are awesome, man!😆

**Comment by jamesblasco** [comment]
Yess you could copy all the SelectionText in your package and use that one instead of the official Flutter Widget. 

But this probably will be launched officially with another api in the following months, so I don't think I will publish a package about it

**Comment by renntbenrennt** [comment]
@jamesblasco hey, man is there anything I can do to help you with that merge? https://github.com/flutter/flutter/pull/66785
it seems it's stalled...
